#+title: Marcel Campello's Emacs Configuration
#+author: Marcel Campello

* Ancillary macros and functions

#+begin_src emacs-lisp
  (defmacro set-mode (mode value)
    "Call a '-mode' function with 'value' as its argument, if this function exists."
    `(when (fboundp ',mode)
       (funcall ',mode ,value)))

  (defmacro enable (mode)
    "Call the '-mode' function with 1 as its argument, thus enabling this mode."
    `(set-mode ,mode 1))

  (defmacro disable (mode)
    "Call the '-mode' function with -1 as its argument, thus disabling this mode."
    `(set-mode ,mode -1))

  (defun reload-config ()
    "Reload the init.el file, thus reloading all the configuration."
    (interactive)
    (let ((init-file (expand-file-name "init.el"
                                       user-emacs-directory)))
      (load-file init-file))
    (message "configuration reloaded"))

  (defun emacs-d (filename)
    "Expand FILENAME relative to 'user-emacs-directory'."
    (expand-file-name filename
                      user-emacs-directory))
#+end_src

* General configuration

** GUI tweaking

Remove distracting elements.
#+begin_src emacs-lisp
  (disable menu-bar-mode)
  (disable tool-bar-mode)
  (disable scroll-bar-mode)
  (disable horizontal-scroll-bar-mode)
#+end_src

Font configuration.
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(font . "Hurmit Nerd Font Mono 10"))
#+end_src

Allow frames to be resized pixelwise.
#+begin_src emacs-lisp
  (setq frame-resize-pixelwise t)
#+end_src

Maximize frame.
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

** Text presentation

Enable visual mode globally (split each long logical line into two or more screen lines).
#+begin_src emacs-lisp
  (enable global-visual-line-mode)
#+end_src

Line and column numbering.
#+begin_src emacs-lisp
  (enable line-number-mode)
  (enable column-number-mode)

  (setq display-line-numbers-width-start t)
  (enable global-display-line-numbers-mode)
#+end_src

Line highlighting.
#+begin_src emacs-lisp
  (enable global-hl-line-mode)
#+end_src

** Input control

Use SPACE only for indentation.
#+begin_src emacs-lisp
  (setq-default indent-tabs-mode nil)
#+end_src

Set TAB character width.
#+begin_src emacs-lisp
  (setq-default tab-width 4)
#+end_src

** Disable backup and auto-save

#+begin_src emacs-lisp
  (setq make-backup-files nil)
  (setq auto-save-default nil)
  (setq auto-save-list-file-prefix nil)
#+end_src

* Package management

** Configure ~package~

Require ~package~.
#+begin_src emacs-lisp
  (require 'package)
#+end_src

Prevent it from messing with ~init.el~.
#+begin_src emacs-lisp
  (setq package--init-file-ensured t
        custom-file (emacs-d "custom-file.el"))
  (when (file-exists-p custom-file)
    (load custom-file))
#+end_src

Configure and initialize it.
#+begin_src emacs-lisp
  (add-to-list 'package-archives
               '("melpa" . "https://melpa.org/packages/"))

  (setq package-archive-priorities '(("melpa" . 20)
                                     ("gnu" . 10)))
  (package-initialize)
#+end_src

** Configure use-package

#+begin_src emacs-lisp
  (eval-when-compile
    (require 'use-package))

  (require 'bind-key)
  (require 'use-package-ensure)
  (setq use-package-always-ensure t)
#+end_src

* Org mode

** General configuration

#+begin_src emacs-lisp
  (setq org-special-ctrl-a/e t)
  (setq org-special-ctrl-o t)
  (setq org-special-ctrl-k t)
  (setq org-ctrl-k-protect-subtree t)
  (setq org-src-window-setup 'current-window)
#+end_src

** Turn on automatic indentation

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook #'org-indent-mode)
#+end_src

** Enabling Org Bullets

Org-bullets gives us attractive bullets rather than asterisks.
#+begin_src emacs-lisp
  (use-package org-bullets

    :hook
    (org-mode . (lambda ()
                  (enable org-bullets-mode))))
#+end_src

** Source Code Block Tag Expansion
Org-tempo is not a separate package but a module within org that can be enabled.  Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag. Other expansions available include:

| Typing the below + TAB | Expands to ...                         |
|------------------------+----------------------------------------|
| <a                     | #+begin_export ascii ... #+end_export  |
| <c                     | #+begin_center ......... #+end_center  |
| <C                     | #+begin_comment ........ #+end_comment |
| <e                     | #+begin_example ........ #+end_example |
| <E                     | #+begin_export ......... #+end_export  |
| <h                     | #+begin_export html .... #+end_export  |
| <l                     | #+begin_export latex ... #+end_export  |
| <q                     | #+begin_quote .......... #+end_quote   |
| <s                     | #+begin_src ............ #+end_src     |
| <v                     | #+begin_verse .......... #+end_verse   |

#+begin_src emacs-lisp
  (require 'org-tempo)
#+end_src

* System integration

** pinentry

#+begin_src emacs-lisp
  (use-package pinentry

    :custom
    (epg-pinentry-mode 'loopback)

    :config
    (pinentry-start))
#+end_src

* Visual

** doom & doom-modeline

#+begin_src emacs-lisp
  (use-package doom-themes

    :config
    (doom-themes-visual-bell-config)
    (doom-themes-org-config)
    (load-theme 'doom-molokai t)

    :custom
    (doom-themes-enable-bold t)
    (doom-themes-enable-italic t))

  (use-package doom-modeline

    :init
    (enable doom-modeline-mode)

    :custom
    (doom-modeline-column-zero-based nil)
    (doom-modeline-position-column-line-format '("L:%l-C:%c"))
    (doom-modeline-enable-word-count t))
#+end_src

* Programming

** VCS

*** git

#+begin_src emacs-lisp
  (use-package magit

    :config
    (defun my-change-repo ()
      (interactive)
      (let ((dir (magit-read-repository)))
        (magit-mode-bury-buffer)
        (magit-init dir)))

    :bind 
    (("C-x g" . magit)
     ("C-x M-g" . magit-dispatch)
     :map magit-mode-map
     ("R" . my-change-repo)))
#+end_src
